### ISSUE TITLE
When re-loading cartridge repositories are overwritten

### ISSUE THREAD

**Issue by michael-t-dukes** [Accenture/adop-platform-management#13]
This is typically the scenario below:

1. I create a new project and load the cartridge (which loads in the jobs and the repositories)
2. I update the repositories for code/config etc
3. I re-run the cartridge as I've made a change on the Jenkins job, and it overwrites my repository to the base

Maybe we could flag overwrite and default it to false?

Then maybe later down the line, maybe adding support to pull the "core" and merge the repository from github into your local ADOP (more advanced).

**Comment by SachinKSingh28** [comment]
Fixed in #17 .
