### ISSUE TITLE
Support embedded cartridges

### ISSUE THREAD

**Issue by kramos** [Accenture/adop-platform-management#16]
Pom files don't get their own repo.  Perhaps Cartridges don't always need on either.  How about the cartridge loader goes a recursive find for the first metadata.cartridge file and it finds and treats that as the cartridge root?

Happy to implement but only if you'll accept this.

I recognise I will need to think about avoiding the repo getting loaded twice (once as the local copy of the cartridge and once if someone re-states it in the urls.txt file).

**Comment by anton-kasperovich** [comment]
I like the idea, don't see much value to sync and keep **all** cartridges by default in my Gerrit  👍

**Comment by anton-kasperovich** [comment]
@SachinKSingh28 @nickdgriffin what do you think guys?

**Comment by kramos** [comment]
Created a PR: #18

**Comment by kramos** [comment]
PR #18 was accepted, this is done!
