### ISSUE TITLE
Extensible choice editable dropdown for the cartridge URL?

### ISSUE THREAD

**Issue by kramos** [Accenture/adop-platform-management#27]
Jenkins already has the extensible choice plugin:
https://wiki.jenkins-ci.org/display/JENKINS/Extensible+Choice+Parameter+plugin

As you can see here:
https://wiki.jenkins-ci.org/download/attachments/65669637/extensible-choice-parameter-global-configuration.png?version=1&modificationDate=1431758568000
It supports editable dropdowns.

This would mean people can load custom cartridges without editing the job.

The only downside I see is that the extensible choice plugin doesn't natively support job dsl, so this would take a:
`configure { project ->`
style insert in the DSL to get it working.

Happy to do this but only if the PR would be accepted.

/cc @anton-kasperovich @nickdgriffin

**Comment by kramos** [comment]
Ok following on from @dsingh07 telling me about this way of generating DSL:
https://github.com/jenkinsci/job-dsl-plugin/wiki/Automatically-Generated-DSL
I had a go.

Unfortunately, I didn't succeed so far.  I tried this:

 ```
       extensibleChoiceParameterDefinition {
            name='CARTRIDGE_CLONE_URL'
            choiceListProvider {
                textareaChoiceListProvider {
                    choiceListText('cart1\cart2')
                    defaultChoice('Top')
                    addEditedValue(false)
                    whenToAdd('triggered')
                 }
            }
            editable(true)
            description('Cartridge URL to load')
        }
```

But despite the generated documentation saying:

` whenToAdd(String value)`

I get this error loading it:

```
ERROR: (script, line 15) No signature of method: javaposse.jobdsl.plugin.structs.DescribableContext.whenToAdd() is applicable for argument types: (java.lang.String) values: [triggered]
Finished: FAILURE
```

Looking at the source code for the extensible choice plugin, it seems an emum is expected:
https://github.com/jenkinsci/extensible-choice-parameter-plugin/search?utf8=%E2%9C%93&q=whenToAdd

I tried various failed attempts to pass in an enum called whenToAdd with a value triggered but no joy.

No cigar.

**Comment by nickdgriffin** [comment]
Did you try doing something like this?

`import jp.ikedam.jenkins.plugins.extensible_choice_parameter.AddEditedChoiceListProvider.WhenToAdd

      extensibleChoiceParameterDefinition {
           name='CARTRIDGE_CLONE_URL'
           choiceListProvider {
               textareaChoiceListProvider {
                   choiceListText('cart1\cart2')
                   defaultChoice('Top')
                   addEditedValue(false)
                   whenToAdd(WhenToAdd.Triggered)
                }
           }
           editable(true)
           description('Cartridge URL to load')
       }
`

I think it's probably just a case where the automatic generation won't work, because even if the correct string is passed in it's not converting it back to the actual enum object that is expected :(

**Comment by kramos** [comment]
No luck, also tried just up to the class and just up to the package:
```
script: 1: unable to resolve class jp.ikedam.jenkins.plugins.extensible_choice_parameter.AddEditedChoiceListProvider.WhenToAdd
 @ line 1, column 1.
   import jp.ikedam.jenkins.plugins.extensible_choice_parameter.AddEditedChoiceListProvider.WhenToAdd
   ^
```

**Comment by kramos** [comment]
Thanks to some help from @robertnorthard we at least proved:
1. Failed imports do not cause an error
2. The import is actually failing due the class requiring system groovy (and job dsl loader doesn't run as system)
3. The inside of the whenToAdd method assumes objects are properties of type describable context, so just going Triggered doesn't work...
ConfigBlock drawing nearer...........

**Comment by kramos** [comment]
Raised a defect against the api-viewer on the dsl plugin:
https://issues.jenkins-ci.org/browse/JENKINS-41270

Hope it helps...

**Comment by kramos** [comment]
Done: https://github.com/Accenture/adop-platform-management/pull/29 !
