### ISSUE TITLE
Error while running Project_Management/Generate_Project job in newly setup Gen5 platform

### ISSUE THREAD

**Issue by avneem** [Accenture/adop-platform-management#46]
Hi Team,

I am facing below error while running Generate_Project job in newly setup Gen5 instance. Please help me out with this ASAP as its impacting client deliverable timelines:

Processing DSL script jobs.groovy
[ssh-agent] Stopped.
ERROR: (jobs.groovy, line 30) No signature of method: javaposse.jobdsl.dsl.helpers.BuildParametersContext.extensibleChoiceParameterDefinition() is applicable for argument types: (jobs$_run_closure2_closure4_closure9) values: [jobs$_run_closure2_closure4_closure9@63f207a9]
Finished: FAILURE

**Comment by RobertNorthard** [comment]
Hi @avneem did you find a solution to this issue?

**Comment by avneem** [comment]
hi , please close the issue. its Not applicable anymore.
