### ISSUE TITLE
[Modification_request] Authorize Job to copy artifact from other job

### ISSUE THREAD

**Issue by dimitri-fert** [Accenture/adop-platform-management#7]
Hello,

I've just deployed the platform on a fresh Debian VM. When I've commit my modification of the spring-petclinic example project by a git commit (and so, triggered the pipeline) the job "Reference_Application_Code_Analysis" failed with the following error:

`ERROR: Unable to find a build for artifact copy from: Reference_Application_Unit_Tests`

I've solved this issue by manually allowing the artifacts from the _Reference_Application_Unit_Tests_ job to get copied by the _Reference_Application_Code_Analysis_ job. This options is displayed in the job configuration screen and is provided by the "Copy Artifacts" plugin.

If the problem is confirmed, the groovy file should be probably modified accordingly.

Thanks

**Comment by nickdgriffin** [comment]
I think this issue probably lives over at: https://github.com/Accenture/adop-cartridge-java

Is the problem that it doesn't have permission to copy the artefacts or that it's just not configured correctly?

**Comment by dimitri-fert** [comment]
Hey nick, I'm sorry but after analysis, it seems that this issue has nothing to do with the conf itself. 

The job _Reference_Application_Code_Analysis_ was unable to find the artifacts from the _Reference_Application_Unit_Tests_ as it was looking for the artifacts from the same build number. Fact is I've manually re-built some job so there's a skip in the builds numbers (Project B #12 trying to use artifact from Project A build #12 but project A has only 5 builds). We can close this ticket.
